# Generated by Django 3.0.8 on 2020-09-10 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200910_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date_published'),
            preserve_default=False,
        ),
    ]
