# Generated by Django 3.0.8 on 2020-09-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20200918_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
    ]
