# Generated by Django 3.0.8 on 2020-09-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20200918_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-pub_date',)},
        ),
    ]
